### ISSUE TITLE
Rails 4.0 Support

### ISSUE THREAD

**Issue by yankeenjg** [wvk/railsdav#3]
The docs mention that this gem is supported for Rails 3. Are there any plans to upgrade and support Rails 4.0?

**Comment by wvk** [comment]
Someone else already tried to port it to rails 4 but I have no Idea whether they succeeded. I did merge those changes into my wvk/railsdav#master and you are welcome to try it out. If you encounter any specific problems, feel free to contact me again. Currently I have no plans to port the gem to Rails 4 for my own needs, but I'd be happy to help if people "out there" are in need for it.

**Comment by yankeenjg** [comment]
Great thanks! I will try it out and let you know if I run into any problems. 

Are those changes reflected on the ruby gems repository? (I think the latest version is 0.0.7 there)

**Comment by ngordon17** [comment]
So I've figured out that the rubygem repository is about a year and a half behind. Would you mind submitting the latest version there?

**Comment by wvk** [comment]
not at all, just pushed 0.0.8 to rubygems repo. I hope nothing breaks.

**Comment by ngordon17** [comment]
Thanks for the quick reply and the push!

I was getting this error with the previous version and still now with the updated one:

`rails-root/config/routes.rb:19:in block in <top (required)>' undefined method  dav_propfind for #<ActionDispatch::Routing::Mapper:0x00003e725392f0> (NoMethodError)`

From this line in my routes.rb file.
`dav_propfind "/resources/*path", to: "resources#index"`

Any ideas why?

**Comment by wvk** [comment]
please try putting this in your routes.rb, the routing extensions are not automatically loaded (I just figured out ...)

```
require 'railsdav/routing_extensions'
```

**Comment by ngordon17** [comment]
Hey awesome, that seems to have fixed that problem! Thanks for all the help!

I'm running into a new one now :/

```
LoadError (cannot load such file -- railsdav/renderer/resource_descriptor):
  app/controllers/folders_controller.rb:37:in `block (3 levels) in show'
  app/controllers/folders_controller.rb:36:in `each'
  app/controllers/folders_controller.rb:36:in `block (2 levels) in show'
  app/controllers/folders_controller.rb:35:in `block in show'
  app/controllers/folders_controller.rb:33:in `show'
```

The route in routes.rb

```
webdav_resources :folders
```

And here's the code in my controller:

```
require 'railsdav'

def show
  @resource = resource

  respond_to do |format|
    format.html
    format.webdav do |dav|
      @resource.children.each do |entry|
        dav.subresource( 
          folder_path(entry), 
          updated_at: entry.updated_at.httpdate,
          size: 0
        )
      end
    end
  end
end
```

**Comment by wvk** [comment]
are you still using 0.0.7 or does that problem persist in 0.0.8? I thought I fixed that yesterday...

**Comment by ngordon17** [comment]
I pulled 0.0.8 from rubygems I believe. The issue from yesterday was related to the routing_extensions.rb file. This seemed to be related to renderers/resource_descriptor.rb file.

**Comment by ngordon17** [comment]
Hey, i realized that the newest version is actually 0.0.9 which was pushed yesterday! I downloaded that any now everything works perfectly! Thanks again for the help! 
Sorry about that.
