### ISSUE TITLE
undefined method webdav_resources

### ISSUE THREAD

**Issue by richardrails** [wvk/railsdav#4]
can't run the Rails 5.2.0 app (ruby 2.5.0), I get error:
undefined method `webdav_resources' for #<ActionDispatch::Routing::Mapper:0x00000000041b3588> (NoMethodError)

```ruby
Rails.application.routes.draw do

  namespace :webdav do
    webdav_resources :projects
  end
end
```

**Comment by richardrails** [comment]
Traceback (most recent call last):
        81: from bin/rails:4:in `<main>'
        80: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        79: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        78: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        77: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        76: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        75: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        74: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        73: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        72: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
        71: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
        70: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
        69: from /home/rf/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        68: from /home/rf/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        67: from /home/rf/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        66: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
        65: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
        64: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        63: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:51:in `start'
        62: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
        61: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
        60: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:27:in `app'
        59: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
        58: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        57: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
        56: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
        55: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
        54: from config.ru:in `<main>'
        53: from config.ru:in `new'
        52: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
        51: from /home/rf/.rvm/gems/ruby-2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
        50: from config.ru:3:in `block in <main>'
        49: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
        48: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
        47: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        46: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
        45: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        44: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        43: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        42: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        41: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        40: from /home/rf/projects/dag/config/environment.rb:5:in `<main>'
        39: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
        38: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
        37: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        36: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        35: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        34: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
        33: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
        32: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        31: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        30: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        29: from /home/rf/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        28: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        27: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
        26: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
        25: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
        24: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:33:in `execute_if_updated'
        23: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:44:in `updater'
        22: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/file_update_checker.rb:83:in `execute'
        21: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:43:in `block in updater'
        20: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:20:in `reload!'
        19: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `load_paths'
        18: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `each'
        17: from /home/rf/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `block in load_paths'
        16: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
        15: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
        14: from /home/rf/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
        13: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
        12: from /home/rf/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
        11: from /home/rf/projects/dag/config/routes.rb:1:in `<main>'
        10: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:414:in `draw'
         9: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
         8: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
         7: from /home/rf/projects/dag/config/routes.rb:18:in `block in <main>'
         6: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1558:in `namespace'
         5: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:946:in `namespace'
         4: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:1832:in `path_scope'
         3: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:947:in `block in namespace'
         2: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:878:in `scope'
         1: from /home/rf/.rvm/gems/ruby-2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:947:in `block (2 levels) in namespace'
/home/rf/projects/dag/config/routes.rb:19:in `block (2 levels) in <main>': undefined method `webdav_resources' for #<ActionDispatch::Routing::Mapper:0x00000000041b3588> (NoMethodError)

**Comment by wvk** [comment]
did you explicitely 

    require 'railsdav/routing_extensions'

?

**Comment by richardrails** [comment]
Yes, I had to.

**Comment by richardrails** [comment]
Now it is working, but I had to require all libs manually also in controller

**Comment by wvk** [comment]
I removed the autoload statements and explicitely require those dependencies now. You should be fine without requiring anything except railsdav itself now (in version 0.1.4).

**Comment by richardrails** [comment]
It works like a charm now. Thank you
